// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YourDailyWord.Data;

namespace YourDailyWord.Data.Migrations
{
    [DbContext(typeof(YourDailyWordDbContext))]
    [Migration("20180415223525_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YourDailyWord.Data.Models.WordGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BibleVerse");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("WordGalleries");
                });

            modelBuilder.Entity("YourDailyWord.Data.Models.WordTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("WordGalleryId");

                    b.HasKey("Id");

                    b.HasIndex("WordGalleryId");

                    b.ToTable("WordTags");
                });

            modelBuilder.Entity("YourDailyWord.Data.Models.WordTag", b =>
                {
                    b.HasOne("YourDailyWord.Data.Models.WordGallery")
                        .WithMany("Tags")
                        .HasForeignKey("WordGalleryId");
                });
#pragma warning restore 612, 618
        }
    }
}
