// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YourDailyWord.Data;

namespace YourDailyWord.Data.Migrations
{
    [DbContext(typeof(YourDailyWordDbContext))]
    [Migration("20180426011930_Fifth Migration")]
    partial class FifthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YourDailyWord.Data.Models.DailyDevotionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description1");

                    b.Property<string>("Description2");

                    b.Property<string>("Description3");

                    b.Property<string>("Description4");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Title");

                    b.Property<string>("Verse");

                    b.Property<string>("VerseTitle");

                    b.HasKey("Id");

                    b.ToTable("DailyDevotionInfos");
                });

            modelBuilder.Entity("YourDailyWord.Data.Models.WordGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description1");

                    b.Property<string>("Description2");

                    b.Property<string>("Description3");

                    b.Property<string>("IndexUrl");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.Property<string>("Verse1");

                    b.Property<string>("Verse2");

                    b.Property<string>("Verse3");

                    b.HasKey("Id");

                    b.ToTable("WordGalleries");
                });

            modelBuilder.Entity("YourDailyWord.Data.Models.WordTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("WordGalleryId");

                    b.HasKey("Id");

                    b.HasIndex("WordGalleryId");

                    b.ToTable("WordTags");
                });

            modelBuilder.Entity("YourDailyWord.Data.Models.WordTag", b =>
                {
                    b.HasOne("YourDailyWord.Data.Models.WordGallery")
                        .WithMany("Tags")
                        .HasForeignKey("WordGalleryId");
                });
#pragma warning restore 612, 618
        }
    }
}
